blueprint:
  name: Zigbee Wireless Switch (single, double, hold)
  description: 'Control anything using Zigbee Wireless Switch'
  domain: automation
  input:
    switch:
      name: Switch
      description: Action sensor of Aqara Wireless Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt

    press_single:
      name: Single button press
      description: Action to run on single button press
      default: []
      selector:
        action: {}
    
    press_double:
      name: Double button press
      description: Action to run on double button press
      default: []
      selector:
        action: {}
    
    press_hold:
      name: Hold button press
      description: Action to run on hold button press
      default: []
      selector:
        action: {}
    

mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input switch
  attribute: click

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
      
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input press_single
      
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input press_double
      
      - conditions:
          - "{{ command == 'hold' }}"
        sequence: !input press_hold
      
