blueprint:
  name: ZHA - Tuya TS0043 3 button remote
  description: Automate your Tuya TS0043 3 button remote using
    ZHA events.
  domain: automation
  input:
    remote:
      name: Tuya TS0043 3 button remote
      description: Tuya TS0043 3 button remote to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_one_single_press:
      name: Button 1 (single press)
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Button 1 (double press)
      description: Action to run on button 1 double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Button 1 (long press)
      description: Action to run on button 1 long press
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: Button 2 (single press)
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Button 2 (double press)
      description: Action to run on button 2 double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Button 2 (long press)
      description: Action to run on button 2 long press
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: Button 3 (single press)
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Button 3 (double press)
      description: Action to run on button 3 double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Button 3 (long press)
      description: Action to run on button 3 long press
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote

action:
  - variables:
      event: "{{ trigger.to_state.state }}"
  - choose:
    - conditions:
        - "{{ event == 1_single }}"
      sequence: !input 'button_one_single_press'
    - conditions:
        - "{{ event == 1_double }}"
      sequence: !input 'button_one_double_press'
    - conditions:
        - "{{ event == 1_hold }}"
      sequence: !input 'button_one_long_press'
    - conditions:
        - "{{ event == 2_single }}"
      sequence: !input 'button_two_single_press'
    - conditions:
        - "{{ event == 2_double }}"
      sequence: !input 'button_two_double_press'
    - conditions:
        - "{{ event == 2_hold }}"
      sequence: !input 'button_two_long_press'
    - conditions:
        - "{{ event == 3_single }}"
      sequence: !input 'button_three_single_press'
    - conditions:
        - "{{ event == 3_double }}"
      sequence: !input 'button_three_double_press'
    - conditions:
        - "{{ event == 3_hold }}"
      sequence: !input 'button_three_long_press'
